# Example git checkout from Ansible Playbooks
# To run this, name this file ansible-playbook03_ and run the following in the same directory
# ansible-playbook  ansible-playbook03_git_clone.yml  -i hosts
---
- hosts: all
  tasks:
      - name: clone repo 
        git:
         repo: 'https://boschpeter:Peter\!2020@github.com/boschpeter/ansible.git'
         dest: /home/boscp08/Projects/scratch/virtual-insanity/ansible