# To run this, name this file ansible-playbook05_install_mysql.yml and run the following in the same directory
# ansible-playbook  ansible-playbook02_git_clone.yml  -i hosts -K
---
- hosts: dingofarm_workers
  tasks:
      - name: Ensure repo is up-to-date
        git:
            repo: git@github.com:boschpeter/ansible.git
            dest: /home/boscp08/Projects/scratch/virtual-insanity

# https://www.jeffgeerling.com/blog/2018/cloning-private-github-repositories-ansible-on-remote-server-through-ssh
