# To run this, name this file ansible-playbook05_install_mysql.yml and run the following in the same directory
# ansible-playbook  ansible-playbook01_apt_update.yml  -i hosts  -k -K
---
  - hosts: all
    become: true
    tasks: 

      