# To run this, name this file ansible-playbook05_install_mysql.yml and run the following in the same directory
# ansible-playbook  -l dingofarm_workers -i hosts  ansible-playbook05_install_mysql.yml  -k -K
---
  - hosts: all
    become: yes
    tasks: 
    - name: Install packages
      apt:
        name:
        - mysql-server
        - mysql-client
        state: latest
        cache_valid_time: 3600    # update cache if more than an hour old