# To run this, name this file ansible-playbook05_install_mysql.yml and run the following in the same directory
# ansible-playbook  -l dingofarm_workers -i hosts  ansible-playbook01_apt_update.yml  -k -K
---
  - hosts: all
    become: true
    tasks: 
    - name: Update and upgrade apt packages
      apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 #One day