# To run this, name this file vm_touch.yml and run the following in the same directory
# ansible-playbook  -l dingofarm_workers vm_touch.yml  
- hosts: all
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
      path: "/home/boscp08/devops_server.txt"
      state: touch